// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvodAxnMZQRGOWalEXChnypJpJ-ec8wlM',
    appId: '1:799403140660:web:594e4f3b8f401967488c61',
    messagingSenderId: '799403140660',
    projectId: 'qrep-2b501',
    authDomain: 'qrep-2b501.firebaseapp.com',
    storageBucket: 'qrep-2b501.appspot.com',
    measurementId: 'G-G58NK2ZBGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5-ms2nYniA8WJseAk9FqLjhCGsS9oIf4',
    appId: '1:799403140660:android:2a88b04545ae6886488c61',
    messagingSenderId: '799403140660',
    projectId: 'qrep-2b501',
    storageBucket: 'qrep-2b501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBjPA8yrq6oe-40iiid3WRVUUXaMP5S2I',
    appId: '1:799403140660:ios:9494ee94c45794dd488c61',
    messagingSenderId: '799403140660',
    projectId: 'qrep-2b501',
    storageBucket: 'qrep-2b501.appspot.com',
    iosClientId:
        '799403140660-kfb9ang4e417jd1j6p4fk7i03r3p6c4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBjPA8yrq6oe-40iiid3WRVUUXaMP5S2I',
    appId: '1:799403140660:ios:9494ee94c45794dd488c61',
    messagingSenderId: '799403140660',
    projectId: 'qrep-2b501',
    storageBucket: 'qrep-2b501.appspot.com',
    iosClientId:
        '799403140660-kfb9ang4e417jd1j6p4fk7i03r3p6c4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrep',
  );
}
